image:
  repository: ghcr.io/feron-tech/qoscope-measurement-tools
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  iperfTcpNodePort: 32402
  iperfUdpNodePort: 32403
  udpPingNodePort: 32404
  owampNodePort: 32405
  twampNodePort: 32406
  pschedulerNodePort: 32407
