apiVersion: v1
kind: Service
metadata:
  name: nanomq-service
  labels:
    app_matcher: nanomq
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mqtt
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app_matcher: nanomq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nanomq
  labels:
    app_matcher: nanomq
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: "nanomq-service"
  selector:
    matchLabels:
      app_matcher: nanomq
  template:
    metadata:
      labels:
        app_matcher: nanomq
    spec:
      containers:
        - name: nanomq
          image: {{ index .Values "image" "repository" }}:{{ index .Values "image" "tag" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mqtt
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
