[supervisord]
nodaemon=true

[program:iperf3]
command=/usr/bin/iperf3 --server
autorestart=true
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:udpserver]
directory=/opt/udp-ping
command=/opt/udp-ping/udpServer
autorestart=true
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
