apiVersion: v1
kind: Service
metadata:
  name: example-app-service
  labels:
    app_matcher: example-app
spec:
  type: NodePort
  ports:
  - name: example-app-nodeport
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
  selector:
    app_matcher: example-app
---
apiVersion: v1
kind: Secret
metadata:
  name: ci-registry-cred
data:
  .dockerconfigjson: 'ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJjaS50bm8ubmw6NDU2NyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiWjJsMGJHRmlLMlJsY0d4dmVTMTBiMnRsYmkweE1qQXhPbWRzWkhRdFZqaEJOMjlDUjJkdVRUUXpWMUJMVTBOcmRFUT0iCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgImNpLnRuby5ubCI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiWjJsMGJHRmlLMlJsY0d4dmVTMTBiMnRsYmkweE1qQXhPbWRzWkhRdFZqaEJOMjlDUjJkdVRUUXpWMUJMVTBOcmRFUT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg=='
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-app
  labels:
    app_matcher: example-app
spec:
  replicas: 1
  serviceName: "example-app-service"
  selector:
    matchLabels:
      app_matcher: example-app
  template:
    metadata:
      labels:
        app_matcher: example-app
    spec:
      containers:
        - name: example-app
          image: {{ index .Values "image" "repository" }}:{{ index .Values "image" "tag" }}
          ports:
            - containerPort: 80
      imagePullSecrets:
          - name: ci-registry-cred
